# Generated by Django 3.1.1 on 2020-10-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201027_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecomment',
            name='activity',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
            preserve_default=False,
        ),
    ]
