# Generated by Django 3.1.1 on 2020-10-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_movierecomment_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecomment',
            name='activity',
            field=models.CharField(default='1', max_length=3),
            preserve_default=False,
        ),
    ]
