# Generated by Django 3.1.1 on 2020-10-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_movierecomment_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecomment',
            name='runtime',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
